### ISSUE TITLE
Markdown Preview 2.0 RoadMap

### ISSUE THREAD

**Issue by facelessuser** [revolunet/sublimetext-markdown-preview#393]
Roadmap is being posted here for discussion and to let people know what is *currently* being planned.

- [x] Do not vendor Python Markdown.  Python Markdown will be acquired via the current `markdown` dependency.

- [x] Python Markdown configuration changes:
    - No more defining settings as `extension(option1=a,option2=b)`.  Options will be defined as a dictionary. This is the officially recommended convention in Python Markdown. This makes internal settings handling much easier.
   - You will have to define the full extension name: `markdown.extensions.codehilite`.  We've been using a hack to maintain the old include name convention.  Now that we will use the `markdown` dependency, we won't have that hack anymore, and nor do we want to.  This will allow you to import any extension you want outside of Markdown Preview.

- [x] New line to `<br>` conversion will be dropped from GitHub emulation as GitHub no longer does this. Ref issue #374.

- [x] Originally a couple `pymdownx-extension` extensions were ported over to this plugin to give 
 a GitHub-ish feel to Markdown, these will no longer be included directly, but they will be included via dependency.  This will provide the latest versions, and also provide new extensions previously not included. Ref issue #378.

- [x] Drop ST2 so we no longer have to provide specially crafted Python Markdown versions when we try to upgrade.

- [x] Improve yaml front matter parsing: see issue #392.

- [x] Better UML JavaScript injection.  Currently we provide a script that works with flowchart.js and sequence-diagram.js, but there are scenarios where it won't work as well.  Provide updated script that injects UML at a higher level to ensure in visible elements and it gets the correct typeset, and then inject it back into the proper section.  This is similar to how others handle dynamically generated SVG content.

- [x] Link contributors in readme.

- [x] Remove "magic" Pygments configuration.  User will now explicitly configure Pygments CSS injection separately.

- [x] Require explicit parser name moving forward instead of `default`, but provide a deprecation path for the short term.

- [x] Fix GitHub header ID generation.  GitHub only lowercases ASCII chars.

- [x] Ensure default parser is Python Markdown, and enable auto-reload by default.

- [x] General refactoring and cleanup

- [x] Hopefully better documentation.

- [x] Make flake8 compatible. I'd put it up on travis for continuous integration, but I don't have that kind of control.

Possibly more

**Comment by facelessuser** [comment]
I'll elaborate why I plan on changing the settings convention for Python Markdown extensions:

1. The old way of of setting extension options via `extension(option1=a,option2=b)` only allows strings numbers, and booleans.  Arrays, dictionaries, functions are all not supported.  But, some extensions take those type of settings.

2. Keep the settings in JSON allows you to then pass in arrays and dictionaries, but functions cannot  be passed in without essentially coming up with our own notation and then adding logic to the walk the JSON structures looking for that syntax and then importing the described function.  The `pyyaml` library, which we use, already supports a notation of prefixing the function name with `!!python/name:` to pass in functions.

3. The reason me must go from an extension declaration of `codehilite` to `markdown.extensions.codehilite` is simply because Python Markdown abandoned this notation a while ago, and we had been hacking in support for the old way in our vendored Markdown.

Because of these reasons, It makes sense to just provide a setting to load Python Markdown extension settings from a YAML file.  So the plan is that Markdown Preview will get rid of the `enabled_extensions` setting, and instead have a setting called `markdown_extensions` that points to a yml file: `Packages/Markdown Preview/markdown-preview.yml`. It will contain contain like this:

```yml
markdown_extensions:
  - markdown.extensions.smart_strong
  - markdown.extensions.footnotes
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.tables
  - markdown.extensions.abbr
  - markdown.extensions.toc
  - markdown.extensions.meta
  - markdown.extensions.sane_lists
  - markdown.extensions.smarty
  - markdown.extensions.wikilinks
  - markdown.extensions.admonition
  - pymdownx.extrarawhtml
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.gemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      alt: short
      options:
        attributes:
            align: absmiddle
            height: 20px
            width: 20px
        image_path: https://assets-cdn.github.com/images/icons/emoji/unicode/
        non_standard_image_path: https://assets-cdn.github.com/images/icons/emoji/
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.superfences
```

To make it easy on people, it is just a list of extensions.  If you have options to set, you instead make that entry a dictionary within the list (see `pymdownx.emoji`), and add your options.  Here you can see we can configure complex settings with functions and complex structures.

**Comment by facelessuser** [comment]
Because yaml frontmatter can override settings, and the frontmatter is yaml, I think we could also allow `markdown_extensions` to not only be a string point to a yaml file, but it could be directly defined as the yaml structure.

```yml
---
    # Builtin values
    references:
        - references.md
        - abbreviations.md
        - footnotes.md

    destination: destination.html

    # Meta Data
    title: Test Page
    author:
        - John Doe
        - Jane Doe

    # Settings overrides
    settings:
        enable_uml: true
        markdown_extensions:
          - markdown.extensions.footnotes
          - markdown.extensions.attr_list
          - markdown.extensions.def_list
          - markdown.extensions.tables
          - markdown.extensions.abbr
          - markdown.extensions.toc
          - markdown.extensions.smarty
          - markdown.extensions.meta
          - markdown.extensions.wikilinks
          - markdown.extensions.admonition
          - markdown.extensions.codehilite:
              guess_lang: false
              pygments_style: github
          - pymdownx.extrarawhtml
          - pymdownx.progressbar
          - pymdownx.github
          - pymdownx.caret:
              superscript: false
---
```

Most of the work is currently done.  I'd like to evaluate some old settings and see if we can clarify them or get rid of confusing or redundant settings.   The `pymdownx` dependency is not on Package Control yet, so I need to get that up first before we could release this as well.

Current work is here: https://github.com/revolunet/sublimetext-markdown-preview/tree/dev.

**Comment by facelessuser** [comment]
Turns out we don't need to require the extensions to be in yaml.  It was way easier to handle custom objects in JSON than I thought.

All it took was:

```py
def extended_decode(d):
    """Decode python functions."""

    if '!!python/name' in d:
        parts = d["!!python/name"].split('.')
        function = parts[-1]
        module = '.'.join(parts[:-1])
        return getattr(importlib.import_module(module), function)
    return d
```
and

```py
    def parse_md_ext(self):
        extensions = self._sub_settings.get('markdown_extensions', {})
        return json.loads(json.dumps(extensions), object_hook=extended_decode)
```

For this to work:

```js
    "markdown_extensions": [
        "markdown.extensions.smart_strong",
        "markdown.extensions.footnotes",
        "markdown.extensions.attr_list",
        "markdown.extensions.def_list",
        "markdown.extensions.tables",
        "markdown.extensions.abbr",
        "markdown.extensions.toc",
        "markdown.extensions.meta",
        "markdown.extensions.sane_lists",
        "markdown.extensions.smarty",
        "markdown.extensions.wikilinks",
        "markdown.extensions.admonition",
        "pymdownx.extrarawhtml",
        "pymdownx.superfences",
        "pymdownx.tilde",
        {
            "pymdownx.emoji": {
                "emoji_index": {"!!python/name": "pymdownx.emoji.gemoji"},
                "emoji_generator": {"!!python/name": "pymdownx.emoji.to_png"},
                "alt": "short",
                "options": {
                    "attributes": {
                        "align": "absmiddle",
                        "height": "20px",
                        "width": "20px"
                    },
                   "image_path": "https://assets-cdn.github.com/images/icons/emoji/unicode/",
                   "non_standard_image_path": "https://assets-cdn.github.com/images/icons/emoji/"
                }
            }
        },
        "pymdownx.magiclink",
        "pymdownx.tasklist",
        "pymdownx.superfences"
    ],
```

**Comment by facelessuser** [comment]
`pymdown-extensions` is now on Package Control completing that requirement.

**Comment by revolunet** [comment]
Nice cleanup coming ! 👍 

cool that we can keep the JSON settings :)

On the user side, i'm wondering if we shouldn't default to the builtin markdown parser with autosave and livereload enabled.

But as discussed in #371 we dont want to enable API calls on save by default when using github API.

So maybe a setting per parser ?

**Comment by facelessuser** [comment]
> On the user side, i'm wondering if we shouldn't default to the builtin markdown parser with autosave and livereload enabled.

I agree and think the builtin markdown parser should be the default.  I think we could make autoreload on by default except when github has no auth key.  To enable autoreload on github with no auth key, we could provide an additional setting as a safeguard.  Or we could just always not allow autoreload with no auth key.

**Comment by facelessuser** [comment]
I'm also thinking about removing some redundant settings like `enable_highlight`, `enable_pygments`, `guess_language`.  These settings I think should be applied directly to the specific extension in `markdown_extensions`.  It will allow us to clean up internal code as we have to provide less magic.

**Comment by facelessuser** [comment]
Went ahead and removed `enable_highlight` and `enable_pygments`, so this will be directly controlled in extension configuration. Took out all the scanning of extensions for Pygments info as well. Instead, users will configure Pygments CSS injection separately in the settings.

This makes the code much easier to maintain.  The goal is to take out some of the confusing "magic" and make it more clear how things operate.  Also makes it easier to document as there aren't so many situations with exceptions.

Updated roadmap with this and other discussed changes.

**Comment by facelessuser** [comment]
Auto-reload will now be enabled by default moving forward except when the parser is `github` **and** their is no auth token provided.  If auto-reload is desired with github, you must provide an auth token.  This will hopefully prevent the usual issues being opened complaining that they got an error message because they exceeded the GitHub API limitation with no auth token.

**Comment by facelessuser** [comment]
I'm also going to no longer specify the default parser as `default` and instead specify it as `markdown`.  I will most likely deprecate `default` so it will work in the short term, and then can be removed in the future. It just doesn't provide a benefit like `default` does with browser.  Might as well explicitly define it in the settings so it is clear what is meant.

**Comment by facelessuser** [comment]
Will also fix github header id generation.  Apparently, GitHub only lowercases ASCII chars.

File path conversion, base64 conversion, and critic markup, and header id generation is all based on my work from pymdownx, so I will most likely just pull in latest fixes from there via a direct import instead of continuing to port it over.

**Comment by facelessuser** [comment]
@revolunet, from what I can tell, the `SSL` stuff under lib isn't getting used.  Do we still need the SSL libraries?

**Comment by revolunet** [comment]
Not sure, i guess its ST2 legacy

**Comment by facelessuser** [comment]
@revolunet, if you are interested, and you go over to [Travis CI](https://travis-ci.org/) and enable Markdown Preview in it, and then enable the setting "build only if .travis.yml is present", I can enable flake8 linting of python moving forward to help keep the code looking clean.  Continuous integration on open source repos is free, but I don't have the permissions to enable that.

![screen shot 2017-06-14 at 7 38 21 am](https://user-images.githubusercontent.com/1055125/27135076-d8a63a88-50d4-11e7-84f7-0c14b90c2f29.png)

If you don't want continuous integration, we can skip this.  This would open the door to running other tests automatically if we come up with any.

**Comment by revolunet** [comment]
thanks this is done !

**Comment by facelessuser** [comment]
Great!  I'll get it configured sometime later today and make sure it is working.

**Comment by facelessuser** [comment]
It's all setup for linting now.

**Comment by facelessuser** [comment]
Hopefully I can get this finished this month.  I've been a bit distracted by other things.

**Comment by jrappen** [comment]
I just noticed that the `github_oauth_token` setting doesn't show a popup with PackageDev. While at it, maybe you could run over the setting descriptions, too.

**Comment by facelessuser** [comment]
It's probably because there is no default for the oauth. I'm also working on documenting all the settings and will most likey reduce the settings description in the settings file to more simplified notes.

**Comment by adoussot** [comment]
Are you planning to integrate mermaid UML diagram injection in sublimetext-markdown-preview ? 

- sources
    + https://mermaidjs.github.io/
    + [vscode mermaid implementation extension](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid)
- pros
    + I find it much clearer to represent diagram since it doesn't compelled you to have an Start/End nodes as in flowchart.js

**Comment by jrappen** [comment]
Besides:

* <https://github.com/knsv/mermaid>

others come to mind as well:

* <https://github.com/adrai/flowchart.js>
* <https://github.com/bramp/js-sequence-diagrams>
* <https://github.com/plantuml/plantuml>
  * via <https://gitlab.com/graphviz/graphviz>
    * via <https://github.com/mdaines/viz.js>
* <https://github.com/drom/wavedrom>
* <https://github.com/vega/vega> and <https://github.com/vega/vega-lite>
* <https://github.com/stathissideris/ditaa>

**Comment by facelessuser** [comment]
> * [ ] <https://github.com/adrai/flowchart.js>
> * [ ] <https://github.com/bramp/js-sequence-diagrams>

We already support this

> * [ ] <https://github.com/knsv/mermaid>

This can already be supported: https://github.com/facelessuser/pymdown-extensions/issues/60

> * [ ] <https://github.com/plantuml/plantuml>
>  * [ ] <https://gitlab.com/graphviz/graphviz>
>    * [ ] <https://github.com/mdaines/viz.js>

Plant UML can technically be supported, I've done as much as a test with mdpopups which uses pymdown-extensions.

> * [ ] <https://github.com/drom/wavedrom>
> * [ ] <https://github.com/vega/vega> and <https://github.com/vega/vega-lite>
> * [ ] <https://github.com/stathissideris/ditaa>
> * [ ] <https://github.com/partageit/vegetables>
>   * [ ] <https://github.com/partageit/markdown-to-slides>

I have spent no time of these

> Are you planning to integrate mermaid UML diagram injection in sublimetext-markdown-preview ? > If not, do you see some blocking points to integrate it ?

Now this is the real question.  I have not intentions to  specifically implement mermaid JS and pymdown-extension configs, but in the new version, you will be able to write your own mermaid JS and setup pymdown-extensions to do that if you wish.

As for other implementations, you are free to explore and implement whatever you like via the Markdown Preview, but I just don't have time to implement everyone's favorite flavor of UML.

I've been meaning to finish this up for a bit, but with all I have going on, I just haven't had time to finish the documentation.  70% or our issues are usually questions asking how to do something that we have a setting for but just isn't documented well.  But I hate writing documentation, and then get distracted by other stuff, so this keeps dragging out...go figure.

**Comment by facelessuser** [comment]
I've now cleared out some time to finish this up.  I'm hoping to have the documentation done over the weekend.

After the documentation is done, I'll need to go over everything again and make sure everything is covered and I don't have any obvious corner cases that I haven't covered.

**Comment by facelessuser** [comment]
I'm pretty much done with documentation.  Just need to update changelog and upgrade message and I'll probably pull this.

I'll need to create an ST2 branch and we'll need to decide if we want to actively support distributing ST2 releases through package control.  My personal opinion is to cut off ST2, but we'll see.

**Comment by facelessuser** [comment]
I am done with the everything in the roadmap, and at this point consider work done.  I'm ready to release, but just need to settle on our release strategy moving forward.  2.0 is for ST3 only, and we need to decide whether we will continue to support ST2 with releases, or just provide an unmaintained branch.  Discussion is taking place over at #391.  Once this is settled, we can merge this work over and  release.

**Comment by facelessuser** [comment]
Considering that I will most likely be taking ownership of this for the immediate future, there are a couple of additional changes I will be making before the next release.

I've felt there are a bit too many features that don't make sense to continue supporting in the way they are currently supported.  For instance, MathJax and UML support.  We already have a feature that includes custom JS and CSS, and yet we have a MathJax feature option and UML feature option that simply includes JavaScript and/or CSS to support UML and MathJax.  Users may want to include their own variations, so I will most likely remove the UML and MathJax options, and in turn require the users to simply include the desired MathJax and/or UML configuration and support files via the js and css configuration options.  As the Markdown Preview package is zipped, we may be able to make such assets available via `ref://Packages/Markdown Preview/js/file.js`. We would resolve internally the path and extract and include it.

I want to also evaluate some of these other options and make sure we want to support them the same way moving forward.

If I am to support this, I want to simplify the support.

**Comment by facelessuser** [comment]
`skip_default_stylesheet` is another option that can get removed.  With the `css` option how it currently is, you can simply remove `default` from the array (or any CSS) and you'll get the same effect.  This option is redundant, and with the big, breaking changes in 2.0, this is the time to strip it.

Probably should rename `embed_css_for_sublime_output` as well. Really what this does (if set false) is skip output of the head, and instead only outputs the body.  I don't really recall where this came from, and I'm not huge fan of this feature.  It's such a narrow use case of only stripping the head for Sublime output.  What about other output modes? I'll take a look and consider what to do with this one.  I feel like this should get reworked to either be more general, or simply removed, but I may not do that at this  time.

I don't see any reasons to remove other settings.

**Comment by facelessuser** [comment]
Okay, recent changes are done.  Also implemented a document site for github pages.  This is ready to go.
